
[[battery.display]]
threshold = 10
style = "bold red"

[character]
success_symbol = "[Î»](bold #BE95FF)" #% $ Î» âˆ† âˆ âˆ€ âˆƒ âˆ‚ âˆˆ ğ¿ ğ‡ ğ âˆ‡ ğ›€ 
error_symbol = "[Î»](bold blue)"
vimcmd_symbol = "[âˆ‡](bold green)"

[cmd_duration]
min_time = 10_000  
format = "took [$duration]($style)"
style = "bold bright-black"

[directory]
style = "bold #be95ff"
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
disabled=true

[git_branch]
format = "âˆƒ [$branch]($style)"
style = "bold #be95ff"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "â‰ "
diverged = "Y"
modified = "*"
untracked = "âˆ‰"
up_to_date = "âˆˆ"
style = "bold bright-magenta"
format = " [$all_status]($style) "

[hostname]
disabled = true

[username]
show_always = false

[aws]
disabled=true

[rust]
disabled=true

[docker_context]
disabled=true

[package]
disabled=true

[nodejs]
disabled=true

[lua]
disabled=true
